

name: Xcode Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Xcode
      uses: actions/setup-xcode@v2
      with:
        xcode-version: '12.5'
    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods
        pod install
    - name: Build and Test
      run: |
        xcodebuild -workspace Null.xcworkspace -scheme Null -destination "platform=iOS Simulator,name=iPhone 12" build test